jenkinsci/customizable-header-plugin

src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly, src/main/webapp/css/custom-header.css
fixes #13 
The `--logo-bg` css var was removed from core and dark theme plugin. This caused the wrong background color to be used by the logo link. Use var `--background` instead.
manually verified that `--background` is used and looks as expected
```[tasklist]
```
=> fix logo background

src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly
The height was not properly set for svg logo when thin header is disabled
```[tasklist]
```
=> Fix height for SVG logo when not thin

src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly
the Icon logo should not be used as logo as icons are basically outdated. The icon class is still required in the context aware header.
fixes #28
```[tasklist]
```
=> remove the Icon logo from the available logos

src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/config.jelly
with a textarea editing the system message avoids scrolling in case the entered data is longer (e.g. due to html tags).
fixes #62
```[tasklist]
```
=> use textarea to edit the system message

src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderDecorator.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderDecorator/header.jelly
The theme should not be loaded when the Jenkins Header is used. Either because the Custom header is disabled or because the Jenkins Header is selected globally or via a user setting.
fixes #70
```[tasklist]
```
=> do not apply theme on Jenkins Header

pom.xml, src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java, src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java, src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java, src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly
the alert will take care of the proper coloring and is theme aware. convert the colors to the alert levels, maps
red -> danger
orange -> warning
lightyellow -> info
there is a new level success now.
This change might break CasC when a systemMessage is configured in CasC. Use 
```
configuration-as-code:
deprecated: warn
```
or change `color` to `level` according to above mapping.
```[tasklist]
```
=> use alert for the system message

src/main/java/io/jenkins/plugins/customizable_header/AppNavLink.java, src/main/js/app-nav/index.js, src/main/resources/io/jenkins/plugins/customizable_header/AppNavLink/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/AppNavLink/help-external.html, src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly
make it configurable if a link opens in a new tab or not. Use a small icon to symbolize the behaviour.
fixes #76
```[tasklist]
```
=> external links

src/main/resources/io/jenkins/plugins/customizable_header/headers/JenkinsHeader/headerContent.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly, src/main/webapp/css/header.css
as the the alert classes from Jenkins collide with those from boostrap, on some pages the system message is styled differently. This also affects admin monitors but this is out of control, To avoid this use selve defined classes that make use of the jenkins defined colors
fixes #99
See [JENKINS-73114](https://issues.jenkins.io/browse/JENKINS-73114)
```[tasklist]
```
=> workaround JENKINS-73114

README.md, pom.xml, src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java, src/main/java/io/jenkins/plugins/customizable_header/HeaderRootAction.java, src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java, src/main/java/io/jenkins/plugins/customizable_header/UserHeader.java, src/main/java/io/jenkins/plugins/customizable_header/headers/SystemMessageProvider.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderDecorator/header.jelly, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/help-expireDate.html, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/index.jelly, src/main/resources/io/jenkins/plugins/customizable_header/flatpickr.css, src/main/resources/io/jenkins/plugins/customizable_header/flatpickr.js, src/main/resources/io/jenkins/plugins/customizable_header/headers/JenkinsHeader/headerContent.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly, src/main/webapp/css/header.css, src/main/webapp/js/messages.js
You can now define multiple system messages. Each message can have an expiration time. Messages can be dismissed on a per user basis.
fixes #112 
fixes #110
=> multiple expiring system messages (#110, #112)

src/main/java/io/jenkins/plugins/customizable_header/UserHeader.java
when an existing user is loaded via xstream, dismissedMessages is not initialized when it is not contained in the xml. This then always throws an null error and system messages can't be shown.
=> fix null in userheader dismissed

pom.xml, src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderDecorator/header.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/JenkinsHeader/headerContent.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly
since 2.459 core provides the logo, search box and login parts of the header via a taglib for easier reuse in plugins.
This avoids that we have to duplicate the code and do double maintenance.
```[tasklist]
```
=> use header taglib to decouple from core

pom.xml, src/main/java/io/jenkins/plugins/customizable_header/HeaderRootAction.java, src/main/java/io/jenkins/plugins/customizable_header/UserHeader.java
most likely caused when updating the plugin after user specific links where added. In that case the links field is not initialized.
Also fix issue with overwriting header and colors not getting properly saved.
fixes #152
=> fix NPE in user config reconfigure

package-lock.json, pom.xml, yarn.lock
In trying to add this plugin to [bom](https://github.com/jenkinsci/bom), I was unable to run:
`mvn clean verify`
locally to do testing since I did not have `npm` installed:
```
[INFO] --- frontend:1.15.0:yarn (yarn mvnbuild) @ customizable-header ---
[INFO] Running 'yarn run mvnbuild' in /Users/dpope/github-forks/customizable-header-plugin
[INFO] yarn run v1.22.19
[INFO] $ npm run build
[INFO] /bin/sh: npm: command not found
[INFO] error Command failed with exit code 127.
[INFO] error Command failed with exit code 127.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
There may be a better way to solve this issue, but this was the simplest way for me.
Once this issue is solved (in whatever way you prefer), I can add this plugin to bom.
`mvn clean …
=> Add `npm` install in order to add to bom

src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java
When a user has never saved his configuration, there is no userHeader property. This leads to a NPE when checking for links.
fixes #169
=> fix NPE when UserHeader not found

src/main/java/io/jenkins/plugins/customizable_header/AppNavLink.java
For the header logo the ionicons-api plugin is searched by default when no plugin is defined. Apply the same behavior for usage of symbols in links to conform to the help.
fixes #173
Manual interactive testing
=> use ionicons-api as default plugin for links as well

README.md, src/main/java/io/jenkins/plugins/customizable_header/HeaderRootAction.java, src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/help-dismissible.html, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/index.jelly, yarn.lock
each system message can be configured to be dismissible or not. 
fix #160
=> Allow disabling dismiss of system messages

src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/help-systemMessage.html, src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly, src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/config.jelly, src/main/webapp/help-systemMessage.html
Use a set or radio button with a label that has the look of the system message instead of a drop down
fixes #181 
Before: 
After:
=> Improve UI to select level of system messages

README.md, pom.xml, src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java, src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/help-title.html, src/main/webapp/help-systemMessage.html, src/test/java/io/jenkins/plugins/customizable_header/SystemMessageTest.java, src/test/java/io/jenkins/plugins/customizable_header/headers/AbstractLogoHeaderTest.java, src/test/java/io/jenkins/plugins/customizable_header/headers/ContextAwareHeaderTest.java, src/test/java/io/jenkins/plugins/customizable_header/headers/LogoHeaderTest.java
See #182 for more details.
This can be considered a breaking change in case users relied on `RawHtmlMarkupFormatter` to format the texts and have a different global `MarkupFormatter` (e.g. `EscapedMarkupFormatter`) configured. 
However I think this behavior is way more consistent as plugins should not need to by-pass the global `MarkupFormatter`.
fix #182
Added tests to show that titles and messages are properly escaped using the global `MarkupFormatter`.
=> Use global MarkupFormatter for headers and system message

src/main/java/io/jenkins/plugins/customizable_header/headers/ContextAwareHeader.java, src/main/java/io/jenkins/plugins/customizable_header/headers/JenkinsHeader.java, src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java, src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderDecorator/header.jelly, src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly, src/main/webapp/css/header.css
- make the JenkinsHeader a partial header as it in fact depends on things defined in core
- when plugin not enabled don't return the JenkinsHeader of the plugin. In that case it's anyway not possible to define system messages or links
- ensure the css for system messages is always included so that after enabling the plugin the type for system messages is already properly shown
=> minor bugs fixing

src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly, src/main/resources/lib/customizable-header/systemMessages.jelly, src/main/webapp/css/header.css
The search box was too close to the table when scrolled at top.
Also adds even more margin below the header
=> wrap system messages in div to improve sticky app bar on plugin manager pages

src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java
With datadog plugin installed the call to save in readResolve triggers the saveable listener of the datadog plugin which then results in loading the current user. This tries to read the header configuration which is not yet properly initialized. The effect is that the header config is not there later breaking the UI completely.
fixes #219
=> Fix plugin loading when datadog is installed

pom.xml, src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java, src/main/java/io/jenkins/plugins/customizable_header/color/HeaderColor.java, src/main/java/io/jenkins/plugins/customizable_header/headers/JenkinsHeaderSelector.java, src/main/java/io/jenkins/plugins/customizable_header/headers/JenkinsWrapperHeaderSelector.java, src/test/java/io/jenkins/plugins/customizable_header/CasCTest.java, src/test/resources/io/jenkins/plugins/customizable_header/casc-jenkins-header.yaml, src/test/resources/io/jenkins/plugins/customizable_header/casc-old-context-aware-header.yaml, src/test/resources/io/jenkins/plugins/customizable_header/casc-old-jenkins-header.yaml, src/test/resources/io/jenkins/plugins/customizable_header/casc-old-logo-header.yaml, src/test/resources/io/jenkins/plugins/customizable_header/casc-sectioned-header.yaml
due to a duplicate symbol loading CasC with `header: "jenkins"`  resulted in the old JenkinsHeaderSelector getting configured. But this no longer works resulting in no header getting applied.
Added CasC tests that loads old and current configs
the hoverColor no longer breaks loading of old CasC configs
fixes #167
=> fix CasC when loading jenkins header

src/main/resources/io/jenkins/plugins/customizable_header/headers/JenkinsWrapperHeader/logo.jelly, src/main/resources/io/jenkins/plugins/customizable_header/headers/SectionedHeader/headerContent.jelly
Small one to hide header titles on mobile. The title can cause the header to overflow, resulting in a broken mobile experience (see weekly.ci.jenkins.io on mobile).
---
**Before**
**After**
* Title appears on desktop
* Title does not appear on mobile
=> Hide header title on mobile

src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.css.jelly
The margin shows when a background hasn't been set, causing an unnecessary gap between the header and app bar.
**Before**
**After**
=> Remove margin if there's no background

src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.css.jelly
latest weekly had a change in the breadcrumbs of the header. The default margin of the `ol` is now considered, casuing the thin header option to be not really thin anymore when not in the root of Jenkins.
tested that the change doesn't break anything with 2.516.1 and fixes the header with 2.522
=> fix thin header with Jenkins 2.522 and newer
